ACCEPTABLE_INGREDIENTS_DATA_W_UNITS = [
    ["Solid Serving Size", "(g)"],
    ["Volume Serving Size", "(cups)"],
    ["Piece Serving Size", "(pieces)"],
    ["Price per Serving", "($)"],
    ["Calories", "(kcal)"],
    ["Carbohydrate", "(g)"],
    ["Total Fiber", "(g)"],
    ["Protein", "(g)"],
    ["Fat", "(g)"],
    ["Saturated fatty acids", "(g)"],
    ["Trans fatty acids", "(g)"],
    ["alpha-Linolenic Acid", "(g)"],
    ["Linoleic Acid", "(g)"],
    ["Cholesterol", "(mg)"],
    ["Total Water", "(L)"],
    ["Vitamin A", "(mcg)"],
    ["Vitamin C", "(mg)"],
    ["Vitamin D", "(mcg)"],
    ["Vitamin B6", "(mg)"],
    ["Vitamin E", "(mg)"],
    ["Vitamin K", "(mcg)"],
    ["Thiamin", "(mg)"],
    ["Vitamin B12", "(mcg)"],
    ["Riboflavin", "(mg)"],
    ["Folate", "(mcg)"],
    ["Niacin", "(mg)"],
    ["Choline", "(mg)"],
    ["Pantothenic Acid", "(mg)"],
    ["Biotin", "(mcg)"],
    ["Calcium", "(mg)"],
    ["Chloride", "(g)"],
    ["Chromium", "(mcg)"],
    ["Copper", "(mg)"],
    ["Fluoride", "(mg)"],
    ["Iodine", "(mcg)"],
    ["Iron", "(mg)"],
    ["Magnesium", "(mg)"],
    ["Manganese", "(mg)"],
    ["Molybdenum", "(mcg)"],
    ["Phosphorus", "(g)"],
    ["Potassium", "(mg)"],
    ["Selenium", "(mcg)"],
    ["Sodium", "(mg)"],
    ["Zinc", "(mg)"]
]

ACCEPTABLE_INGREDIENTS_DATA_W_UNITS_COMPARABLE = [
    ["solid serving size", "g"],
    ["volume serving size", "cup"],
    ["piece serving size", "pieces"],
    ["price per serving", "$"],
    ["calories", "kcal"],
    ["carbohydrate", "g"],
    ["total fiber", "g"],
    ["protein", "g"],
    ["fat", "g"],
    ["saturated fatty acids", "g"],
    ["trans fatty acids", "g"],
    ["alpha-linolenic acid", "g"],
    ["linoleic acid", "g"],
    ["cholesterol", "mg"],
    ["total water", "l"],
    ["vitamin a", "mcg"],
    ["vitamin c", "mg"],
    ["vitamin d", "mcg"],
    ["vitamin b6", "mg"],
    ["vitamin e", "mg"],
    ["vitamin k", "mcg"],
    ["thiamin", "mg"],
    ["vitamin b12", "mcg"],
    ["riboflavin", "mg"],
    ["folate", "mcg"],
    ["niacin", "mg"],
    ["choline", "mg"],
    ["pantothenic acid", "mg"],
    ["biotin", "mcg"],
    ["calcium", "mg"],
    ["chloride", "g"],
    ["chromium", "mcg"],
    ["copper", "mg"],
    ["fluoride", "mg"],
    ["iodine", "mcg"],
    ["iron", "mg"],
    ["magnesium", "mg"],
    ["manganese", "mg"],
    ["molybdenum", "mcg"],
    ["phosphorus", "g"],
    ["potassium", "mg"],
    ["selenium", "mcg"],
    ["sodium", "mg"],
    ["zinc", "mg"]
]

UNIT_LIST_COMPARABLE = ["oz"]
for i in range(len(ACCEPTABLE_INGREDIENTS_DATA_W_UNITS_COMPARABLE)):
    UNIT_LIST_COMPARABLE.append(ACCEPTABLE_INGREDIENTS_DATA_W_UNITS_COMPARABLE[i][1])


UNIT_PREFIXES_W_VALUE = {"k": 1000, "mc": 0.000001, "m": 0.001, "": 1}

DAILY_RECOMMENDED_VALUES = [
    ["Calories (kcal)", 2000],
    ["Carbohydrate (g)", 275],
    ["Total Fiber (g)", 28],
    ["Protein (g)", 50],
    ["Fat (g)", 78],
    ["Saturated fatty acids (g)", 20],
    ["Trans fatty acids (g)", 2.2],
    ["alpha-Linolenic Acid (g)", 1.6],
    ["Linoleic Acid (g)", 1.6],
    ["Cholesterol (mg)", 300],
    ["Total Water (L)", 3.3],
    ["Vitamin A (mcg)", 900],
    ["Vitamin C (mg)", 90],
    ["Vitamin D (mcg)", 20],
    ["Vitamin B6 (mg)", 1.7],
    ["Vitamin E (mg)", 15],
    ["Vitamin K (mcg)", 120],
    ["Thiamin (mg)", 1.2],
    ["Vitamin B12 (mcg)", 2.4],
    ["Riboflavin (mg)", 1.3],
    ["Folate (mcg)", 400],
    ["Niacin (mg)", 16],
    ["Choline (mg)", 550],
    ["Pantothenic Acid (mg)", 5],
    ["Biotin (mcg)", 30],
    ["Calcium (mg)", 1300],
    ["Chloride (g)", 2300],
    ["Chromium (mcg)", 35],
    ["Copper (mg)", 0.9],
    ["Fluoride (mg)", 3],
    ["Iodine (mcg)", 150],
    ["Iron (mg)", 18],
    ["Magnesium (mg)", 420],
    ["Manganese (mg)", 2.3],
    ["Molybdenum (mcg)", 45],
    ["Phosphorus (g)", 1250],
    ["Potassium (mg)", 4700],
    ["Selenium (mcg)", 55],
    ["Sodium (mg)", 2300],
    ["Zinc (mg)", 11]
]